from __future__ import annotations

import random
import string
from typing import Any, Sequence

from domain_types import Difficulty, JsonScalar
from puzzle import FunctionContract, TestCase
from puzzles.common import (
    require_arity,
    require_str_value,
    require_variable_int,
    sample_pairs_shared_inputs,
)

template_key = "crypto-shift-inference-v2"
theme = "Cryptography"
difficulties: tuple[Difficulty, ...] = ("medium",)
prompt = (
    "A deterministic text transformation is used across this match. "
    "`samples` contains visible (input, output) string pairs generated by that same hidden rule. "
    "Implement solution(arg1, samples) so it applies the same rule to `arg1`."
)
hint_level_1 = (
    "Each letter is transformed independently; punctuation and spaces stay unchanged."
)
hint_level_2 = (
    "One fixed alphabet rotation amount is reused for every case in the match."
)
hint_level_3 = "Infer that rotation from any example letter mapping, then apply it to the input text."
contract = FunctionContract(
    parameter_types=("str", "list[tuple[str, str]]"),
    return_type="str",
    parameter_names=("arg1", "samples"),
)


def shift_char(char: str, shift: int) -> str:
    if "a" <= char <= "z":
        base = ord("a")
        return chr(base + ((ord(char) - base + shift) % 26))
    if "A" <= char <= "Z":
        base = ord("A")
        return chr(base + ((ord(char) - base + shift) % 26))
    return char


def solve_caesar(text: str, shift: int) -> str:
    return "".join(shift_char(char, shift) for char in text)


def variable_factory(
    rng: random.Random, difficulty: Difficulty
) -> dict[str, JsonScalar]:
    shift_span = {"easy": 8, "medium": 12, "hard": 18, "expert": 25}[difficulty]
    shift = rng.randint(1, shift_span)
    if difficulty in {"hard", "expert"} and rng.random() < 0.4:
        shift *= -1
    return {"shift": shift}


def random_text_with_letters(rng: random.Random, length: int) -> str:
    charset = string.ascii_letters + "      ,.!?-"
    chars = [rng.choice(charset) for _index in range(length)]
    if sum(1 for char in chars if char.isalpha()) < 3:
        for _index in range(3):
            chars[rng.randrange(len(chars))] = rng.choice(string.ascii_lowercase)
    text = "".join(chars).strip()
    return text or "abc"


def case_factory(
    rng: random.Random, difficulty: Difficulty, params: dict[str, JsonScalar]
) -> TestCase:
    length = {"easy": 16, "medium": 26, "hard": 40, "expert": 56}[difficulty]
    shift = int(params["shift"])
    source = random_text_with_letters(rng, length)
    return TestCase(inputs=(source,), output=solve_caesar(source, shift))


def shared_input_factory(
    params: dict[str, JsonScalar], sample_tests: list[TestCase]
) -> tuple[Any, ...]:
    return sample_pairs_shared_inputs(params, sample_tests)


def expected_output_for_primary_inputs(
    *,
    variables: dict[str, JsonScalar],
    primary_inputs: Sequence[Any],
) -> Any:
    require_arity(primary_inputs, expected=1)
    text = require_str_value(primary_inputs[0], label="text")
    shift = require_variable_int(variables, name="shift")
    return solve_caesar(text, shift)
