from __future__ import annotations

import random
from typing import Any, Sequence

from domain_types import Difficulty, JsonScalar
from puzzle import FunctionContract, TestCase
from puzzles.common import (
    require_arity,
    require_int_value,
    require_variable_int,
    sample_pairs_shared_scalar_inputs,
)

template_key = "numeric-linear-transform-v1"
theme = "Numeric"
difficulties: tuple[Difficulty, ...] = ("expert",)
prompt = (
    "A deterministic linear transformation is used across this match. "
    "`examples` contains visible [input, output] pairs generated by that same hidden rule. "
    "Implement solution(value, examples) so it applies the same rule to `value`."
)
hint_level_1 = "The hidden rule has the form output = a*x + b."
hint_level_2 = "The same constants a and b are reused for every case in the match."
hint_level_3 = "Infer a and b from sample pairs, then compute a*value + b."
contract = FunctionContract(
    parameter_types=("int", "list[list[int]]"),
    return_type="int",
    parameter_names=("value", "samples"),
)


def variable_factory(
    rng: random.Random, _difficulty: Difficulty
) -> dict[str, JsonScalar]:
    slope = 0
    while slope == 0:
        slope = rng.randint(-15, 15)
    intercept = rng.randint(-120, 120)
    return {"a": slope, "b": intercept}


def case_factory(
    rng: random.Random, _difficulty: Difficulty, params: dict[str, JsonScalar]
) -> TestCase:
    value = rng.randint(-400, 400)
    slope = int(params["a"])
    intercept = int(params["b"])
    return TestCase(inputs=(value,), output=slope * value + intercept)


def shared_input_factory(
    params: dict[str, JsonScalar], sample_tests: list[TestCase]
) -> tuple[Any, ...]:
    return sample_pairs_shared_scalar_inputs(params, sample_tests)


def expected_output_for_primary_inputs(
    *,
    variables: dict[str, JsonScalar],
    primary_inputs: Sequence[Any],
) -> Any:
    require_arity(primary_inputs, expected=1)
    value = require_int_value(primary_inputs[0], label="x")
    a = require_variable_int(variables, name="a")
    b = require_variable_int(variables, name="b")
    return a * value + b
